url: "https://tedserbinski.com"

permalink: /:categories/:title/

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.markdown
  - s3_website.yml
  - .jekyll-metadata
  - .asset-cache
  - .sass-cache
  - .git

# configuration options https://github.com/jekyll/jekyll-assets
assets:
  cdn: https://tedserbinski.com
  prefix: "/assets"
  assets:
    - "christmas-lights.png"
    - "bg.jpg"
  sources:
    - _assets/js
    - _assets/js/vendor
    - _assets/css
    - _assets/css/custom
    - _assets/img
    - _assets/img/headshots
    - _assets/img/posts
    - _assets/img/pages
  features:
    liquid: true

# site config variables
## todo: remove these
tagline_homepage: >
  <p class="tag1">Hello! I'm the Managing Director of <a href="http://www.techstars.com/programs/mobility-program/">Techstars Mobility</a>.</p>
  <p class="tag2">I invest in <a href="/mobility/defining-mobility/">mobility startups</a> changing the future of transportation from downtown Detroit.</p>
  <p class="tag3"><a href="/detroit/the-entrepreneurial-gold-rush-why-i-moved-from-san-francisco-to-detroit/">I left Silicon Valley to fuel the entrepreneurial gold rush in Detroit</a> and create a legacy.</p>

tagline_feed: >
  Ted Serbinski - Ex-Silicon Valley entrepreneur and early stage startup investor fueling the startup renaissance in Detroit.

tagline_copyright: >
  Ted Serbinski. All rights reserved. <a href="https://github.com/tedserbinski/www-tedserbinski-com" title="View  source code to this website">Made with <span style="color: #ff6032;">♥</span> in Detroit, Michigan</a>.

bio_footer: >
  Hi, I'm <a href="https://twitter.com/tedserbinski" rel="author">Ted Serbinski</a>. I live in Metro Detroit and am the Managing Director of <a href="http://www.techstars.com/programs/mobility-program/">Techstars Mobility, driven by Detroit</a>. I love <a href="http://momtomomnutrition.com/">my wife</a> &amp; kids, investing in startups, and contributing to the startup renaissance in Detroit. <a href="/about/">Learn more</a>.

bio_micro: >
  Managing Director, Techstars Mobility, driven by Detroit. Former Partner at Detroit Venture Partners. Ex-Silicon Valley guy leading startup renaissance in Detroit. Cornell Engineering alum. Happily married living in Metroit Detroit with wife and son.

bio_short: >
  Ted Serbinski is an entrepreneur and early stage investor leading the startup renaissance in Detroit. He is the Managing Director of Techstars Mobility, driven by Detroit. Previously he was a Partner and founding team member of Detroit Venture Partners. Ted has co-led investments in 24 companies over the past 3 years, with 13 of those headquartered in Detroit.

  Before moving to Detroit from San Francisco, Ted was a co-founder and CTO of ParentsClick. With the 4th largest social network and the largest blog network for moms online, Lifetime Television acquired ParentsClick in 2008.

  Ted graduated from Cornell in 2004, with a B.S. in Computer Engineering.

  Ted resides in Metro Detroit with his beautiful wife and son.

bio_regular: >
  Ted Serbinski is an entrepreneur and early-stage investor. As an ex-Silicon Valley guy, he moved to Detroit to create a legacy and help lead the startup renaissance in Detroit. He is the Managing Director of Techstars Mobility, driven by Detroit. Previously, he was a Partner and founding team member of Detroit Venture Partners. Ted has co-led investments in 24 companies over the past 3 years, with 13 of those headquartered in Detroit.

  Ted is active in the Detroit startup community sitting on many boards. Currently he is on the board of the Michigan Venture Capital Association Techtown Detroit, and is the Midwest Regional Advisor for Venture for America. He also was the founding Chairman of the Detroit Executive Advisory Board of Techweek. The inaugural event in May 2014 attracted nearly 2000 attendees as the largest startup tech event in Detroit.

  Before moving to Detroit from San Francisco, Ted was a co-founder and CTO of ParentsClick. With the 4th largest social network and the largest blog network for moms, Lifetime Television acquired ParentsClick in 2008.

  Ted graduated from Cornell in 2004, with a B.S. in Computer Engineering.

  He currently resides in Metro Detroit with his beautiful wife and son.

  Ted blogs on startups, technology, and Detroit at <a href="https://tedserbinski.com">https://tedserbinski.com</a>.
